Jupyter messaging updates/correctness
JuliaLang/IJulia.jl pull request #1138
Opened 2024-12-19 00:37 UTC by halleysfifthinc

- Bump Julia compat to be able to use `pkgversion` in `"kernel_info_request"` to report the IJulia version
- Some messages and responses were sent on the wrong channel:
  - Replies should be sent to the channel the request was sent on
    - This is not :100: explicit in the messaging protocol docs, but appears to be the norm. Some messages are only described as always being sent (by the frontend/client) on a specific channel, but e.g. I saw `"kernel_info_request"` sent on both the shell/requests channel *AND* the control channel. (The latter is not described as possible according to the docs.)
- Replies should [always](https://jupyter-client.readthedocs.io/en/latest/messaging.html#request-reply) have a `{ 'status': 'ok' }`
- The `transient` metadata field was added in protocol version 5.1. Without the ability to add transient metadata, `"update_display_data"` messages can't be used to update/redisplay existing outputs (while participating in/with the rest of the IJulia display machinery). Related PR #946 is more extensive and stalled; this is the minimum necessary change to support this.

Fixes #953
Fixes #1000

Reference: https://jupyter-client.readthedocs.io/en/latest/messaging.html

2025-01-13 20:34 UTC, halleysfifthinc commented
Bump

2025-01-29 09:38 UTC, JamesWrigley requested changes
Not strictly necessary for this PR, but we should start using `jupyter_kernel_test` in the tests: https://github.com/jupyter/jupyter_kernel_test

2025-01-29 09:38 UTC, JamesWrigley commented on src/IJulia.jl
> +using Dates: now, format, @dateformat_str, UTC, ISODateTimeFormat
Is `@dateformat_str` needed?

2025-01-29 18:11 UTC, halleysfifthinc commented on src/IJulia.jl
> +using Dates: now, format, @dateformat_str, UTC, ISODateTimeFormat
Ah! No. 
(In an earlier version of this PR I was manually recreating the `ISODateTimeFormat` with the `'Z'` at the end, but that is no longer needed by the current code.)

2025-01-29 19:01 UTC, JamesWrigley approved these changes
LGTM!

2025-01-29 19:02 UTC, merged