Update documentation for installation
JuliaLang/IJulia.jl pull request #966
Opened 2020-12-02 06:19 UTC by willingc

This PR updates the installation documentation based on current Jupyter practices and designates legacy sections where needed. It adds nteract to the intro doc.

2025-06-15 08:17 UTC, JamesWrigley requested changes
Sorry for leaving this for so long @willingc, would you still be willing to rebase and finish it? No worries if not, I can also do it if that's ok with you.

2025-06-15 08:17 UTC, JamesWrigley commented on docs/src/manual/installation.md
> +2. Run the installer for the downloaded version.
We should link to the Install page instead since juliaup is now the recommended way to install Julia: https://julialang.org/install/

2025-06-15 08:17 UTC, JamesWrigley commented on docs/src/manual/installation.md
> +3. Run the Julia application by double-clicking on the icon. This
```suggestion
3. Run the Julia application by double-clicking on the icon or running `julia` in a terminal. This
```

2025-06-18 17:19 UTC, ViralBShah commented
@JamesWrigley It would be great if you could get this in!

2025-06-18 17:23 UTC, willingc commented
Thanks for the ping. It would be great if someone else wants to take it over.

2025-06-19 08:54 UTC, JamesWrigley approved these changes
Thanks @willingc, I took the liberty of making some minor changes but otherwise I think this is a nice improvement.

2025-06-19 08:54 UTC, merged